DROP TABLE course CASCADE CONSTRAINTS;
DROP TABLE grade_report CASCADE CONSTRAINTS;
DROP TABLE prerequisite CASCADE CONSTRAINTS;
DROP TABLE section CASCADE CONSTRAINTS;
DROP TABLE student CASCADE CONSTRAINTS;
